global:
  argocdConfig:
    project: "default"
    namespace: "argocd"
    server: "https://kubernetes.default.svc"

project: "default"

traefik:
  namespace: traefik
  targetRevision: v35.3.0

  replicas: 3
  loadBalancerIP: 192.168.3.80

certManager:
  name: cert-manager
  namespace: cert-manager
  targetRevision: v1.17.2
  replicas: 3

longhorn:
  namespace: longhorn-system
  targetRevision: v1.9.0
  preUpgradeCheckerJobEnabled: false
  storageReplicas: 2
  defaultStorageClass: true
  defaultStorageReplicaCount: 2
  defaultMigratable: true

reflector:
  # Reflector is only used to sync certificates between namespaces
  # so should be in the cert-manager namespace
  # namespace: reflector
  targetRevision: 0.15.0

eks:
  onepasswordConnect:
    namespace: external-secrets
    targetRevision: 1.17.0

  onepasswordOperator:
    namespace: external-secrets
    targetRevision: 0.17.0

kubePrometheusStack:
  namespace: monitoring
  targetRevision: 75.6.1
